# Generated by Django 6.0.3 on 2026-03-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="habit",
            old_name="is_comlited",
            new_name="is_completed",
        ),
    ]
